### ISSUE TITLE
Makefile:14: recipe for target 'init' failed

### ISSUE THREAD

**Issue by fanypa** [aniketpanjwani/chomper#26] opened 2018-03-09 12:21 UTC
##### Steps to reproduce the problem:

1. make init
2.
3.

##### Any other comments? What have you tried so far?

	$ ~/chomper$ make init
	/bin/bash: pipenv: command not found
	pip install pipenv # Install pipenv
	Collecting pipenv
	Collecting pathlib (from pipenv)
	Collecting setuptools>=36.2.1virtualenv (from pipenv)
	  Using cached setuptools-38.5.2-py2.py3-none-any.whl
	Collecting virtualenv-clone>=0.2.5 (from pipenv)
	  Using cached virtualenv_clone-0.3.0-py2.py3-none-any.whl
	Installing collected packages: pathlib, setuptools, virtualenv-clone, pipenv
	Successfully installed pathlib-1.0.1 pipenv-11.1.6 setuptools-38.5.2 virtualenv-clone-0.3.0
	pipenv install --dev # Install packages
	/bin/bash: pipenv: command not found
	Makefile:14: recipe for target 'init' failed
	make: *** [init] Error 127

Not sure how to resolve this "Install packages" error.

##### System information

	$ lsb_release -a

	Distributor ID:	Debian
	Description:	Debian GNU/Linux 9.3 (stretch)
	Release:	9.3
	Codename:	stretch

**Comment by aniketpanjwani** [comment] 2018-03-09 14:51
Thanks for the issue rerpot. I think the problem is that pipenv is not put on your path during installation. Can you try modifying the line `pip install pipenv` to `sudo -H pip install -U pipenv`, and then re-running `make init`?

**Comment by dufywihi** [comment] 2018-03-10 17:06
Hey, I'm also having this problem using the same version of debian. I changed the `pipenv` line in the Makefile as you suggested. Any suggestions?

	$ make init

	sudo -H pip install -U pipenv # Install pipenv
	Requirement already up-to-date: pipenv in /usr/local/lib/python2.7/dist-packages
	Requirement already up-to-date: virtualenv-clone>=0.2.5 in /usr/local/lib/python2.7/dist-packages (from pipenv)
	Requirement already up-to-date: setuptools>=36.2.1 in /usr/local/lib/python2.7/dist-packages (from pipenv)
	Requirement already up-to-date: pathlib in /usr/local/lib/python2.7/dist-packages (from pipenv)
	Requirement already up-to-date: virtualenv in /usr/local/lib/python2.7/dist-packages (from pipenv)
	pipenv install --dev # Install packages
	Warning: Python 3.6 was not found on your system…
	You can specify specific versions of Python with:
	  $ pipenv --python path/to/python
	/home/user/.local/lib/python2.7/site-packages/pipenv/utils.py:1152: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-zflZBs-requirements'>
	  warnings.warn(warn_message, ResourceWarning)
	Makefile:14: recipe for target 'init' failed
	make: *** [init] Error 1


	$ whereis python3

	python3: /usr/bin/python3 /usr/bin/python3.5m-config /usr/bin/python3.5m /usr/bin/python3.5-config /usr/bin/python3.5 /usr/lib/python3 /usr/lib/python3.5 /etc/python3 /etc/python3.5 /usr/local/lib/python3.5 /usr/include/python3.5m /usr/include/python3.5 /usr/share/python3 /usr/share/man/man1/python3.1.gz


	$ cat Makefile 

	# Copyright: (c) 2018, Aniket Panjwani <aniket@addictedto.tech>
	# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

	SHELL:=/bin/bash
	INTERPRETER=$(shell pipenv --py)
	CURRENT_USER:=$(shell whoami)
	CURRENT_DIR:=$(shell pwd)
	SUDOERS_FILE:=/etc/sudoers.d/chomper
	SUDOERS_ENTRY_MIDDLE:=" ALL=(ALL) NOPASSWD: "
	SUDOERS_ENTRY_SUFFIX:="/chomper/block.py *"
	SUDOERS_ENTRY:=$(CURRENT_USER)$(SUDOERS_ENTRY_MIDDLE)$(INTERPRETER) $(CURRENT_DIR)$(SUDOERS_ENTRY_SUFFIX)

	init:
		sudo -H pip install -U pipenv # Install pipenv
		pipenv install --dev # Install packages
		pipenv run mitmdump & sleep 2 && kill -9 $$! # Generate certificates
		openssl x509 -outform der -in ~/.mitmproxy/mitmproxy-ca.pem -out ~/.mitmproxy/mitmproxy-ca.crt
		sudo cp /home/$(CURRENT_USER)/.mitmproxy/mitmproxy-ca.crt /usr/local/share/ca-certificates/mitmproxy-ca.crt # Install root certificates
		sudo update-ca-certificates
		sudo sh ./chomper/certs.sh # Make browsers recognize root certificates
		sudo sysctl -w net.ipv4.ip_forward=1 # Enable ipv4 forwarding
		sudo sysctl -w net.ipv6.conf.all.forwarding=1 # Enable ipv6 forwarding
		sudo sysctl -p # Lock in new ip forwarding settings.

	lock:
		echo $(SUDOERS_ENTRY) | sudo EDITOR='tee' visudo -f $(SUDOERS_FILE)
		sudo chown -R root:root ./
		sudo chown $(CURRENT_USER):$(CURRENT_USER) ./data/rules.yaml
		sudo chown $(CURRENT_USER):$(CURRENT_USER) ./readme.org
		sudo chown $(CURRENT_USER):$(CURRENT_USER) ./.gitignore
		sudo chown -R $(CURRENT_USER):$(CURRENT_USER) ./.git

	reset:
		sudo env PATH=$(PATH):/usr/sbin:/sbin ${INTERPRETER}3.6m ${CURRENT_DIR}/chomper/reset.py

**Comment by aniketpanjwani** [comment] 2018-03-10 19:08
Thanks for the comment! I think that we solved one problem and hit another problem, which is that the Pipfile asks for Python 3.6, but it's not on your system. Again, this is my fault for being too hasty in creating a more fully automated installation in the Makefile.

Let's try two things. One is a temporary hack which will hopefully get you up and running, and the other should be more permanent.

1. In the Pipfile, change python_version 3.6 to 3.5.
2. Install [pyenv](https://github.com/pyenv/pyenv), put it on PATH, install Python 3.6.4, and then try to run `make init` again.

Sorry about this!

**Comment by aniketpanjwani** [comment] 2018-03-10 20:09
Been thinking a bit more on this. I think the correct set of steps is

1. Install pyenv, put it on PATH, and install python 3.6.4 with pyenv.
2. Adjust the `pipenv install --dev` to `pipenv install --dev --python 3.6.4`.

I should update the README to make pyenv a requirement.

**Comment by dufywihi** [comment] 2018-03-10 21:33
Hmmm, would you be able to spin up Debian machine in virtualbox to debug? `pyenv` wasn't found in the pip repositories or in APT repos.

	root@debian:/home/user/chomper# pip install pyenv
	Collecting pyenv
	  Could not find a version that satisfies the requirement pyenv (from versions: )
	No matching distribution found for pyenv
	root@debian:/home/user/chomper# apt-cache search pyenv
	direnv - Utility to set directory specific environment variables
	root@debian:/home/user/chomper# 

Really appreciate your help with this. Full discloser, I'm hoping to feature chomped on tecmint.com in the coming weeks. So I'm looking for a quick (debug-free) installation method that novice tecmint readers can easily digest.

**Comment by aniketpanjwani** [comment] 2018-03-10 22:29
Understood. `pyenv` isn't able to be installed from pip or apt. You need to [clone from git](https://github.com/pyenv/pyenv#installation), or you can use [this automatic installer](https://github.com/pyenv/pyenv-installer) which might automate some of the PATH configuration.

Yes, I'll try spinning up a debian Vagrant VM. I don't know if I can test everything in a VM, since some of the configuration files modified by be shared between the VM and the host computer, but at the very least, I should be able to see that the part of the Makefile we're having trouble with is working properly.

**Comment by aniketpanjwani** [comment] 2018-03-11 02:57
I've created an iss26 branch with a modified Makefile which _should_ work. I'm not able to test the certificate installation without spinning up an AWS instance (since the VM shares certificates), but hopefully this works now. I'd greatly appreciate if you tried out the installation on your system and let me know if it worked.

**Comment by aniketpanjwani** [comment] 2018-03-11 03:06
Here's the Vagrantfile and provisioning script I used to create the VM:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "2048"
    vb.name = "chomper"
    config.vm.provision "shell", path: "provision.sh"
  end
end
```
provision.sh:
```
#!/bin/bash

# Get build tools
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install git build-essential curl zlib1g-dev libbz2-dev libsqlite3-dev libreadline-dev libncurses5-dev libssl-dev libgdbm-dev python-pip

# Clone chomper and install
git clone https://github.com/aniketpanjwani/chomper.git
cd chomper && git checkout iss26
```

**Comment by aniketpanjwani** [comment] 2018-03-12 21:11
I merged the issue 26 branch into master. I'm going to consider this fixed and close the issue, but let me know if it's still not working for you.

**Closed** 2018-03-12 21:11 UTC
Labels: bug
